In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/philippines_tech_jobs_raw.csv")
df.head()

,job_id,job_title,employer_name,employer_logo,employer_website,job_publisher,job_employment_type,job_employment_types,job_apply_link,job_apply_is_direct,...,job_salary_string,job_min_salary,job_max_salary,job_salary_period,job_highlights,job_onet_soc,job_onet_job_zone,employer_reviews,job_uid,search_role
0,RjBxQXYwdkUtbEM2VjBoREFBQUFBQT09OkVzd0JDb3dCUV...,CRM Junior Data Analyst,RUSTAN COMMERCIAL CORPORATION,https://encrypted-tbn0.gstatic.com/images?q=tb...,NaN,Jobstreet,Full-time,['FULLTIME'],https://ph.jobstreet.com/job/94164327,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,F0qAv0vE-lC6V0hDAAAAAA==,Data Analyst
1,TG1zVUxHVHhNX3dyQU1raEFBQUFBQT09OkVzd0JDb3dCUV...,Finance Master Data Lead Analyst,Vestas Services Philippines Inc.,https://t0.gstatic.com/faviconV2?client=SOCIAL...,https://www.vestas.com,Jobstreet,Full-time,['FULLTIME'],https://ph.jobstreet.com/job/94176150,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,LmsULGTxM_wrAMkhAAAAAA==,Data Analyst
2,MVZzYl91azYwUGh0aTIxQUFBQUFBQT09OkVzd0JDb3dCUV...,CRM Data Analyst: Drive Personalization & Camp...,Home Credit Philippines,https://t0.gstatic.com/faviconV2?client=SOCIAL...,https://www.homecredit.ph,BeBee,Internship,['INTERN'],https://bebee.com/ph/jobs/crm-data-analyst-dri...,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,1Vsb_uk60Phti21AAAAAAA==,Data Analyst
3,T2FYOExQeTIyVGpKNlh1akFBQUFBQT09OkVzd0JDb3dCUV...,CRM Data Analyst — Insights for Precision Camp...,KadaKareer,https://t0.gstatic.com/faviconV2?client=SOCIAL...,https://www.kadakareer.com,BeBee,Full-time,['FULLTIME'],https://bebee.com/ph/jobs/crm-data-analyst-ins...,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,OaX8LPy22TjJ6XujAAAAAA==,Data Analyst
4,WWlGM3dHYUwxeFlLTktTN0FBQUFBQT09OkVzd0JDb3dCUV...,Senior Performance Data Analyst - 7471,International Education,https://t0.gstatic.com/faviconV2?client=SOCIAL...,NaN,Jobstreet,Full-time,['FULLTIME'],https://ph.jobstreet.com/job/93994083,False,...,NaN,NaN,NaN,NaN,{},NaN,NaN,NaN,YiF3wGaL1xYKNKS7AAAAAA==,Data Analyst

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 631 entries, 0 to 630
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      631 non-null    str
 1   job_title                   631 non-null    str
 2   employer_name               631 non-null    str
 3   employer_logo               496 non-null    str
 4   employer_website            317 non-null    str
 5   job_publisher               631 non-null    str
 6   job_employment_type         603 non-null    str
 7   job_employment_types        631 non-null    str
 8   job_apply_link              631 non-null    str
 9   job_apply_is_direct         631 non-null    bool
 10  apply_options               631 non-null    str
 11  job_description             631 non-null    str
 12  job_is_remote               631 non-null    bool
 13  job_posted_at               477 non-null    str
 14  job_posted_at_timestamp     477 non-null    float64
 15  job_posted_at_datetime_utc  477 non-null    str
 16  job_location                629 non-null    str
 17  job_city                    408 non-null    str
 18  job_state                   427 non-null    str
 19  job_country                 527 non-null    str
 20  job_latitude                527 non-null    float64
 21  job_longitude               527 non-null    float64
 22  job_benefits                0 non-null      float64
 23  job_benefits_strings        0 non-null      float64
 24  job_google_link             631 non-null    str
 25  job_salary                  0 non-null      float64
 26  job_salary_string           0 non-null      float64
 27  job_min_salary              0 non-null      float64
 28  job_max_salary              0 non-null      float64
 29  job_salary_period           0 non-null      float64
 30  job_highlights              631 non-null    str
 31  job_onet_soc                0 non-null      float64
 32  job_onet_job_zone           0 non-null      float64
 33  employer_reviews            0 non-null      float64
 34  job_uid                     631 non-null    str
 35  search_role                 631 non-null    str
dtypes: bool(2), float64(13), str(21)
memory usage: 169.0 KB

ROLE COUNTS

In [6]:
df["search_role"].value_counts()

search_role
Data Engineer        141
Data Analyst         139
Software Engineer    138
Cloud Engineer       126
Data Scientist        87
Name: count, dtype: int64

CHECK DUPLICATES

In [11]:
df["job_id"].duplicated().sum()

np.int64(0)

In [12]:
df.duplicated().sum()

np.int64(0)

MISSING VALUES

In [14]:
missing_percentage = (df.isnull().mean() * 100).sort_values(ascending=False)

print(missing_percentage)

job_min_salary                100.000000
job_onet_soc                  100.000000
job_salary_period             100.000000
job_max_salary                100.000000
job_benefits                  100.000000
job_benefits_strings          100.000000
job_onet_job_zone             100.000000
employer_reviews              100.000000
job_salary                    100.000000
job_salary_string             100.000000
employer_website               49.762282
job_city                       35.340729
job_state                      32.329635
job_posted_at_datetime_utc     24.405705
job_posted_at_timestamp        24.405705
job_posted_at                  24.405705
employer_logo                  21.394612
job_longitude                  16.481775
job_latitude                   16.481775
job_country                    16.481775
job_employment_type             4.437401
job_location                    0.316957
job_id                          0.000000
job_title                       0.000000
employer_name                   0.000000
job_apply_link                  0.000000
apply_options                   0.000000
job_description                 0.000000
job_is_remote                   0.000000
job_apply_is_direct             0.000000
job_publisher                   0.000000
job_employment_types            0.000000
job_google_link                 0.000000
job_highlights                  0.000000
job_uid                         0.000000
search_role                     0.000000
dtype: float64

In [15]:
df["job_country"].value_counts(dropna=False)

job_country
PH     527
NaN    104
Name: count, dtype: int64

In [24]:
country_missing = df[df["job_country"].isna()]

country_missing[
    [
        "search_role",
        "job_title",
        "employer_name",
        "job_location",
        "job_city",
        "job_state",
        "job_country"
    ]
].head(20)

,search_role,job_title,employer_name,job_location,job_city,job_state,job_country
138,Data Analyst,Data Analyst I (Channel Rebate Data Steward),Schneider Electric,Cavite,NaN,NaN,NaN
226,Data Engineer,Data engineer/ Analyst,"Prime@Technology Specialists, Inc.",Cavite,NaN,NaN,NaN
229,Data Engineer,"Director, Data Engineering",Manulife,"Lapu-Lapu, Cebu (+1 other)",NaN,NaN,NaN
235,Data Engineer,Data Engineer,Cambridge University Press,NaN,NaN,NaN,NaN
285,Data Engineer,"Cloud and Data Engineer (Legaspi, Albay) - Day...",TASQ Staffing Solutions,Bicol (+1 other),NaN,NaN,NaN
417,Cloud Engineer,Cloud Endpoint Support Engineer (Tier 2),HireArchi,Metro Manila (+1 other),NaN,NaN,NaN
418,Cloud Engineer,"Cloud Engineer: Build Resilient, Scalable Infra",Manpower (Philippines),"Valenzuela, Metro Manila",NaN,NaN,NaN
419,Cloud Engineer,Cloud Data Warehouse Engineer - Flexible Hours...,AS White Global,"Taguig, Metro Manila",NaN,NaN,NaN
420,Cloud Engineer,GCP Cloud Engineer (Google Cloud Platform),Brixio Singapore,Philippines,NaN,NaN,NaN
421,Cloud Engineer,"Cloud Network Engineer, Software Support",Copeland,"Quezon City, Metro Manila",NaN,NaN,NaN
422,Cloud Engineer,Senior .NET Cloud Engineer — AI‑Powered Azure ...,Intellectsoft,Philippines,NaN,NaN,NaN
423,Cloud Engineer,"AWS Cloud Engineer | IaC, CI/CD & Security",Orangeandbronze,"Makati City, Metro Manila",NaN,NaN,NaN
424,Cloud Engineer,Lead DevOps Engineer | Fully WFH,RecruitNest Consulting,Metro Manila (+1 other),NaN,NaN,NaN
425,Cloud Engineer,"Observability Engineer — Cloud, Kubernetes",Dsv Air & Sea SAU,"Manila, Metro Manila",NaN,NaN,NaN
426,Cloud Engineer,Lead Cloud Engineer - Infrastructure | REMOTE,TASQ Staffing Solutions,"Cebu City, Cebu",NaN,NaN,NaN
427,Cloud Engineer,Remote Cloud Engineer | AWS,NetCov PH,Davao Region,NaN,NaN,NaN
428,Cloud Engineer,Junior Cloud SRE: AWS,eTap Inc.,"Makati City, Metro Manila",NaN,NaN,NaN
429,Cloud Engineer,Senior Cloud Engineer (Openshift/AWS) - WFH/3 ...,Green Light Worldwide,Philippines,NaN,NaN,NaN
430,Cloud Engineer,Remote IT Systems Engineer: Lead Cloud,Intelligent Technical Solutions,"Quezon City, Metro Manila",NaN,NaN,NaN
431,Cloud Engineer,Senior AWS Cloud Engineer – Remote,TTEC Digital,"Pasig, Metro Manila",NaN,NaN,NaN

In [25]:
missing_all_location = df[
    df["job_country"].isna()
    & df["job_state"].isna()
    & df["job_city"].isna()
    & df["job_location"].isna()
]

print(missing_all_location.shape)

(2, 36)

In [29]:
missing_all_location[
    [
        "search_role",
        "job_title",
        "employer_name",
        "job_description",
        "job_location"
    ]
]

,search_role,job_title,employer_name,job_description,job_location
235,Data Engineer,Data Engineer,Cambridge University Press,Data Engineer\n\nWork setup: We operate in a h...,NaN
556,Software Engineer,"Software Engineer, Platform - Cebu, Philippines",Speechify,The mission of Speechify is to make sure that ...,NaN

In [27]:
description = missing_all_location.loc[235, "job_description"]

print("philippines" in description.lower())
print("manila" in description.lower())
print("cebu" in description.lower())

True
True
False

VERIFY DATES

In [31]:
df["job_posted_at_datetime_utc"] = pd.to_datetime(
    df["job_posted_at_datetime_utc"],
    errors="coerce"
)

In [32]:
print(df["job_posted_at_datetime_utc"].min())
print(df["job_posted_at_datetime_utc"].max())

2026-07-25 00:00:00+00:00
2026-08-25 01:00:00+00:00

### DATA CLEANING

In [33]:
print(df.columns.tolist())

['job_id', 'job_title', 'employer_name', 'employer_logo', 'employer_website', 'job_publisher', 'job_employment_type', 'job_employment_types', 'job_apply_link', 'job_apply_is_direct', 'apply_options', 'job_description', 'job_is_remote', 'job_posted_at', 'job_posted_at_timestamp', 'job_posted_at_datetime_utc', 'job_location', 'job_city', 'job_state', 'job_country', 'job_latitude', 'job_longitude', 'job_benefits', 'job_benefits_strings', 'job_google_link', 'job_salary', 'job_salary_string', 'job_min_salary', 'job_max_salary', 'job_salary_period', 'job_highlights', 'job_onet_soc', 'job_onet_job_zone', 'employer_reviews', 'job_uid', 'search_role']

In [37]:
columns_to_keep = [
    "job_id",
    "search_role",
    "job_title",
    "employer_name",
    "job_publisher",
    "job_employment_type",
    "job_description",
    "job_is_remote",
    "job_posted_at_datetime_utc",
    "job_location",
    "job_city",
    "job_state",
    "job_country"
]

df_clean = df[columns_to_keep].copy()

In [38]:
df_clean["job_posted_at_datetime_utc"] = pd.to_datetime(
    df_clean["job_posted_at_datetime_utc"],
    errors="coerce"
)

In [ ]:
print(df_clean["job_employment_type"].value_counts(dropna=False))

job_employment_type
Full-time                   554
NaN                          28
Internship                   27
Contractor                   17
Part-time                     3
Full-time and Contractor      2
Name: count, dtype: int64
job_is_remote
False    631
Name: count, dtype: int64

In [39]:
print(df_clean["job_is_remote"].value_counts(dropna=False))

job_is_remote
False    631
Name: count, dtype: int64

In [40]:
df_clean["location_clean"] = df_clean["job_location"]

df_clean["location_clean"] = df_clean["location_clean"].fillna(
    df_clean["job_city"]
)

df_clean["location_clean"] = df_clean["location_clean"].fillna(
    df_clean["job_state"]
)

In [42]:
df_clean.loc[
    df_clean["location_clean"].isna(),
    [
        "search_role",
        "job_title",
        "employer_name",
        "job_location",
        "job_city",
        "job_state",
        "job_country"
    ]
]

,search_role,job_title,employer_name,job_location,job_city,job_state,job_country
235,Data Engineer,Data Engineer,Cambridge University Press,NaN,NaN,NaN,NaN
556,Software Engineer,"Software Engineer, Platform - Cebu, Philippines",Speechify,NaN,NaN,NaN,NaN

In [43]:
df_clean.loc[556, "location_clean"] = "Cebu, Philippines"

In [44]:
df_clean.loc[235, "location_clean"] = "Makati, Philippines"

In [47]:
print(df_clean.info())

<class 'pandas.DataFrame'>
RangeIndex: 631 entries, 0 to 630
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_id                      631 non-null    str
 1   search_role                 631 non-null    str
 2   job_title                   631 non-null    str
 3   employer_name               631 non-null    str
 4   job_publisher               631 non-null    str
 5   job_employment_type         603 non-null    str
 6   job_description             631 non-null    str
 7   job_is_remote               631 non-null    bool
 8   job_posted_at_datetime_utc  477 non-null    datetime64[us, UTC]
 9   job_location                629 non-null    str
 10  job_city                    408 non-null    str
 11  job_state                   427 non-null    str
 12  job_country                 527 non-null    str
 13  location_clean              631 non-null    str
dtypes: bool(1), datetime64[us, UTC](1), str(12)
memory usage: 64.8 KB
None

In [55]:
print(df_clean["job_employment_type"].value_counts(dropna=False))

job_employment_type
Full-time                   554
Unknown                      28
Internship                   27
Contractor                   17
Part-time                     3
Full-time and Contractor      2
Name: count, dtype: int64

In [51]:
df_clean["job_employment_type"] = (
    df_clean["job_employment_type"]
    .fillna("Unknown")
    .str.strip()
)

In [52]:
columns_to_drop = [
    "job_min_salary",
    "job_max_salary",
    "job_salary",
    "job_salary_string",
    "job_salary_period",
    "job_benefits",
    "job_benefits_strings",
    "job_onet_soc",
    "job_onet_job_zone",
    "employer_reviews"
]

df_clean = df_clean.drop(columns=columns_to_drop, errors="ignore")

In [54]:
print(df_clean.columns.tolist())

['job_id', 'search_role', 'job_title', 'employer_name', 'job_publisher', 'job_employment_type', 'job_description', 'job_is_remote', 'job_posted_at_datetime_utc', 'job_location', 'job_city', 'job_state', 'job_country', 'location_clean']